sonar.projectKey=collaborator-document-api
sonar.projectName=collaborator-document-api
sonar.sources=src
sonar.tests=tests
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.exclusions=**/node_modules/**,**/dist/**,**/coverage/**,**/docs/typedoc/**
sonar.test.inclusions=tests/**/*.ts
